# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/ubuntu-16.04"
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5050, host: 5050, host_ip: "127.0.0.1"
  
  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  #config.vm.synced_folder "data", "/vagrant_data"
  config.vm.synced_folder "www", "/var/www"
  config.vm.synced_folder "scripts", "/vagrant_data/scripts"
  config.vm.provision "shell", path: "https://gist.githubusercontent.com/rugbyprof/3d1f3aee7febdc05cfe7b1a4e4f96203/raw/4e6964c7012edf8fe0c411cb3533b8f00a5e5d57/vagrant.sh"
  #pip install requests
  #pip install flask
  #pip install flask_cors
  #pip install pymongo

end
